//pages/DeveloperDashboard/utils/developerDashPropertyHelpers.js

export const REQUIRED_FIELDS = [
  "title",
  "description",
  "city",
  "locality",
  "address",
  "pincode",
  "propertyType",
  "furnishing",
  "possessionStatus",
  "price",
  "unitsAvailable"
];

export const initialFormData = {
  developerName: "",
  title: "",
  description: "",
  long_description: "",
  state: "",
  city: "",
  locality: "",
  address: "",
  pincode: "",
  mapLink: "",
  area: { value: 0, unit: "sqft" },
  reraApproved: false,
  reraNumber: "",
  priceNegotiable: false,
  price: "",
  emiStarts: "",
  propertyType: "",
  furnishing: "",
  possessionStatus: "",
  bhk: "",
  bathrooms: "",
  balconies: "",
  facing: "",
  parkings: [],
  ageOfProperty: "",
  totalFloors: "",
  floor: "",
  wing: "",
  unitsAvailable: "",
  reraDate: null,
  amenities: [],
  facilities: [],
  security: [],
  coverImage: "",
  galleryImages: [],
  floorplanImages: [],
  mediaFiles: [],
};

export const normalizePropertyData = (property = {}) => ({
  ...initialFormData,
  ...property,
  area: property.area || { value: 0, unit: "sqft" },
  parkings: Array.isArray(property.parkings) ? property.parkings : [],
  galleryImages: property.galleryImages || [],
  floorplanImages: property.floorplanImages || [],
  mediaFiles: property.mediaFiles || [],
  amenities: property.amenities || [],
  facilities: property.facilities || [],
  security: property.security || [],
  reraApproved: !!property.reraApproved,
  priceNegotiable: !!property.priceNegotiable,
  reraDate: property.reraDate || null,
});